pipeline {
    agent any

    stages {

        stage('build') {
            steps {
              bat '''
                 cd ./admin-api
                 ./mvnw -DskipTests clean compile
              '''
            }
        }

        stage('test') {
            steps {
              bat '''
                 cd admin-api
                     ./mvnw test
              '''
            }
        }

        stage('deliver') {
            steps {
              bat '''
                 cd admin-api
                     ./mvnw -DskipTests install
              '''
            }
        }

    }
}
